### ISSUE TITLE
loading error.

### ISSUE THREAD

**Issue by Larbo53** [inquilabee/TableCV#1]
loading error.

hello,

when loading, the following message appears:
 Could not find a version that satisfies the requirement numpy==1.21.2 
Thanks for your feedback.
sincerely

**Comment by inquilabee** [comment]
I worked on this a lot of months ago. Can you try installing a different numpy version? 

Do you know how to create wheel file? You can clone the repo, download latest version of each package in requirement.txt and use the package. 

Let me know if this helps.

**Comment by inquilabee** [comment]
I checked that numpy==1.21.2 exists. https://numpy.org/doc/stable/release/1.21.2-notes.html

You are most probably not using right Python version.
